//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectCantekGroup.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tableUrun()
        {
            this.tableBilesen = new HashSet<tableBilesen>();
        }
    
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string IslemAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tableBilesen> tableBilesen { get; set; }
    }
}
